In [1]:
myString<-"Hello World"
print(myString)


[1] "Hello World"


In [2]:
for(n in c (2,5,10,20,50)){
x <- stats::rnorm(n)
cat(n, ": ", sum(x^2), "\n", sep = "")
}


2: 3.456203
5: 5.198833
10: 12.17636
20: 14.4738
50: 45.43958


In [3]:
help("if")
f <- factor(sample(letters[1:5], 10, replace = TRUE))
for(i in unique(f)) print(i)


[1] "c"
[1] "a"
[1] "e"
[1] "d"
[1] "b"


In [4]:
factor(sample(letters[1:5], 10, replace = TRUE))
for(i in unique(f)) print(i)


[1] d c d b c b d a d b
Levels: a b c d

[1] "c"
[1] "a"
[1] "e"
[1] "d"
[1] "b"


In [5]:
vtr<-c(2,4,6,8)
vtr

[1] 2 4 6 8

In [6]:
vtr=2:12
vtr


[1]  2  3  4  5  6  7  8  9 10 11 12

In [7]:
class(vtr)

[1] "integer"

In [8]:
v=3.5:10.5
v

[1]  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5

In [9]:
day=c("Mon","Tue","Wed","Thur","Fri","Sat","Sun")
print(day[3])

[1] "Wed"


In [10]:
 print(day[-1])

[1] "Tue"  "Wed"  "Thur" "Fri"  "Sat"  "Sun" 


In [11]:
print(day[c(6,7)])

[1] "Sat" "Sun"


In [12]:
weekend=day[c(6,7)]
weekend

[1] "Sat" "Sun"

In [13]:
weekend=weekend[c(2,3)]
weekend


[1] "Sun" NA

In [14]:
print(day[c(-2,-3)])


[1] "Mon"  "Thur" "Fri"  "Sat"  "Sun" 


In [15]:
rollno=c(1,2,3,4)
name=c("a","b","c","d")
marks=c(90.1,80.1,70.1,60.1)
L=list(rollno,name,marks)
L

[[1]]
[1] 1 2 3 4

[[2]]
[1] "a" "b" "c" "d"

[[3]]
[1] 90.1 80.1 70.1 60.1

In [16]:
mat= matrix(c(1:16),nrow=4,ncol=4)
mat


[,1] [,2] [,3] [,4]
[1,] 1    5     9   13  
[2,] 2    6    10   14  
[3,] 3    7    11   15  
[4,] 4    8    12   16

In [17]:
mat=matrix(c(1:16),nrow=4,ncol=4,byrow=TRUE)
mat

[,1] [,2] [,3] [,4]
[1,]  1    2    3    4  
[2,]  5    6    7    8  
[3,]  9   10   11   12  
[4,] 13   14   15   16

In [18]:
mat=matrix(c('a','a','b','c','b','a'),nrow=2,ncol=3,byrow=TRUE)
mat


[,1] [,2] [,3]
[1,] a    a    b   
[2,] c    b    a

In [19]:
 mat[1,3]

[1] "b"

In [20]:
 mat[,3]

[1] "b" "a"

In [21]:
mat[2,]

[1] "c" "b" "a"

In [22]:
rown=c("row1","row2","row3","row4")
coln=c("col1","col2","col3","col4")
mat=matrix(c(1:16),nrow=4,ncol=4,byrow=TRUE,dimname=list(rown,coln))
mat


col1 col2 col3 col4
row1  1    2    3    4  
row2  5    6    7    8  
row3  9   10   11   12  
row4 13   14   15   16